config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  get 'npo_users/new'
  get 'npo_users/edit'
  get 'npo_users/show'
  get 'npo_users/index'
  get 'npo_users/about'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'pays/edit'
  get 'pays/about'
  get 'account_activations/edit'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'serches/index'
  get 'contacts/new'
  get 'contacts/create'
  root 'static_pages#home'
  get '/about', to: "static_pages#about"
  post '/signup', to: 'users#create', as: 'signup'
  get '/signup', to: 'users#new'
  resources :users, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user_id
end

app/models/npo_user.rb
class NpoUser < ApplicationRecord
  belongs_to :user_id
end

app/models/pay.rb
class Pay < ApplicationRecord
  belongs_to :user_id
  belongs_to :npo_user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_secure_password
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :nick_name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                  format: { with: VALID_EMAIL_REGEX },
                  # 小文字大文字区別せず一意であることの制限をかけている
                  uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }

  def User.digest(string)
   cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                 BCrypt::Engine.cost
   BCrypt::Password.create(string, cost: cost)
 end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/pays_controller.rb
class PaysController < ApplicationController
  def edit
  end
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      remember @user
      flash[:success] = "登録が完了しました"
      redirect_to root_path
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:nick_name, :email, :password,
                                  :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = "")
    base_title = "Gift"
    if page_title.empty?
      base_title
    else
      base_title + " | " + page_title
    end
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/npo_users_helper.rb
module NpoUsersHelper
end

app/helpers/pays_helper.rb
module PaysHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/serches_helper.rb
module SerchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    if (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    @current_user = nil
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <%= image_tag "cm1.jpg" %>
  <div class="footer-inner">
    <div>
      <h1>団体を探す</h1>
      <nav>
        <ul>
          <li><%= link_to "すべての団体から探す", "#" %></li>
          <li><%= link_to "カテゴリーから探す", "#" %></li>
          <li><%= link_to "地域から探す", "#" %></li>
        </ul>
      </nav>
    </div>
    <div>
      <h1>Giftについて</h1>
      <nav>
        <ul>
          <li><%= link_to "サービスについて", about_path %></li>
          <li><%= link_to "募金方法について", pays_about_path, class: "footer-about-pays" %></li>
          <li><%= link_to "掲載希望団体の方へ", npo_users_about_path, class: "footer-about-npo" %></li>
        </ul>
      </nav>
    </div>
    <div>
      <h1>お問い合わせ</h1>
      <nav>
        <ul>
          <li><%= link_to "問い合わせ", "#" %></li>
          <li><%= link_to "よくある質問", "#" %></li>
          <li><%= link_to "ご意見箱", "#" %></li>
        </ul>
      </nav>
    </div>
    <div>
      <h1>会社</h1>
      <nav>
        <ul>
          <li><%= link_to "会社概要", "#" %></li>
          <li><%= link_to "利用規約", "#" %></li>
        </ul>
      </nav>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="inner header-inner">
    <h1><%= link_to "Gift", root_path %></h1>
    <% if logged_in? %>
      <%= form_tag("#", method: "get", class: "header-serch-form serch-common")do %>
        <%= text_field_tag :search, "", placeholder: "  NPO団体名で検索" %>
        <%= button_tag :type => "submit", :title => nil do %>
          <i class="fa fa-search" aria-hidden="true"></i>
        <% end %>
      <% end %>
      <%= link_to "ログアウト", logout_path, method: :delete, class: "header-logout-link" %>
    <!--下の画像のところまとめれる？ -->
      <%= link_to user_path(current_user), class: "header-account-link" do %>
        <% if @current_user.top_image.nil?%>
          <%= image_tag "account.png"%>
        <% else %>
          <%= image_tag @current_user.top_image.to_s %>
        <% end %>
      <% end %>
    <% else %>
      <nav>
        <ul>
          <li><%= link_to "Giftとは", about_path %></li>
          <li><%= link_to "募金方法について", pays_about_path %></li>
          <li><%= link_to "掲載希望団体の方へ", npo_users_about_path %></li>
          <li><%= link_to "お問い合わせ", "#" %></li>
        </ul>
      </nav>
        <%= link_to "新規登録", signup_path, class: "signup-link" %>
        <%= link_to "ログイン", login_path, class: "login-link" %>
    <% end %>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header'%>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer'%>
    </div>
  </body>
</html>